### ISSUE TITLE
Compte rendu Reunion 7/03/2023

### ISSUE THREAD

**Issue by agrignard** [laatabix/I-Maroc#2]
- [x] OD per moyen de transport (pied,voiture, 2 roues, bus+taxis) see issue #4 
 - [x] GIS District with the exact population see issue #5

Story telling
- [ ]  Show the evolution of marrakech de 2008 à 2023 (medina qui perd des habitants au profit d'un quartier excentré) see issue #6 

- [ ] Checker l'exactitude de l'OD pourquoi beaucoup de trip depuis un petit quartier see issue #4

- [ ] Meilleur graphe vizu

- [x] Ligne de bus type plan de bus see #3 

-------------------------------------------------------
SIR

Modèles à différentes échelles. 
- [ ]  Macro OD par quartier toutes les 12h
- [ ] Micro avec les sorites du modèles MarraSim
- [ ] Comokit

**Comment by laatabix** [comment]
- I added the exact population of 2014 (last census) to districts + projections for 2023 and 2030.
- error in population of zones is fixed.

**Comment by laatabix** [comment]
Added OD matrix by aggretae of zones + the mapping agregate-zones

**Comment by laatabix** [comment]
Added generated OD matrices (pedestrians + cars + mopeds + public transport)
+
The gama model used for generation

All matrices are generated based on shares of the bus OD matrix between zones.

**Comment by laatabix** [comment]
Added shapefile of bus lines but needs manual correction

**Comment by laatabix** [comment]
added fixed lines (and stations) of bus, BRT, and taxis

**Comment by agrignard** [comment]
I close this issue as it has been splitted in more atomic ones (#3, #4, #5 and #6)
